var PS={};(function(a){a.arrayMap=function(a){return function(c){for(var e=c.length,d=Array(e),f=0;f<e;f++)d[f]=a(c[f]);return d}};a.refEq=function(a){return function(c){return a===c}};a.showIntImpl=function(a){return a.toString()};a.showStringImpl=function(a){return JSON.stringify(a)}})(PS.Prelude=PS.Prelude||{});
(function(a){var b=PS.Prelude,c=function(a){this.compose=a},e=function(a,b){this["__superclass_Prelude.Semigroupoid_0"]=a;this.id=b},d=function(a){this.map=a},f=function(a){this.eq=a},g=function(a){this.show=a},l={},h=new g(b.showStringImpl),m=new g(b.showIntImpl),k=new c(function(a){return function(b){return function(c){return a(b(c))}}}),r=function(a){return a.pure},n=new d(b.arrayMap),b=new f(b.refEq),p=function(a){return function(b){return a}},q=new e(function(){return k},function(a){return a}),
t=function(a){return a.bind};a.Show=g;a.Eq=f;a.Monad=function(a,b){this["__superclass_Prelude.Applicative_0"]=a;this["__superclass_Prelude.Bind_1"]=b};a.Bind=function(a,b){this["__superclass_Prelude.Apply_0"]=a;this.bind=b};a.Applicative=function(a,b){this["__superclass_Prelude.Apply_0"]=a;this.pure=b};a.Apply=function(a,b){this["__superclass_Prelude.Functor_0"]=a;this.apply=b};a.Functor=d;a.Category=e;a.Semigroupoid=c;a.show=function(a){return a.show};a["=="]=function(a){return a.eq};a.eq=function(a){return a.eq};
a["<>"]=function(a){return a.append};a.append=function(a){return a.append};a.ap=function(a){return function(b){return function(c){return t(a["__superclass_Prelude.Bind_1"]())(b)(function(b){return t(a["__superclass_Prelude.Bind_1"]())(c)(function(c){return r(a["__superclass_Prelude.Applicative_0"]())(b(c))})})}}};a["return"]=r;a[">>="]=function(a){return a.bind};a.bind=t;a.liftA1=function(a){return function(b){return function(c){return(0,a["__superclass_Prelude.Apply_0"]().apply)((0,a.pure)(b))(c)}}};
a.pure=function(a){return a.pure};a.apply=function(a){return a.apply};a["void"]=function(a){return function(b){return(0,a.map)(p(l))(b)}};a["<$>"]=function(a){return a.map};a.map=function(a){return a.map};a.id=function(a){return a.id};a.compose=function(a){return a.compose};a["const"]=p;a.flip=function(a){return function(b){return function(c){return a(c)(b)}}};a.unit=l;a.semigroupoidFn=k;a.categoryFn=q;a.functorArray=n;a.eqString=b;a.showInt=m;a.showString=h})(PS.Prelude=PS.Prelude||{});
(function(a){var b=PS.Prelude;a["=<<"]=function(a){return function(e){return function(d){return b[">>="](a)(d)(e)}}}})(PS["Control.Bind"]=PS["Control.Bind"]||{});
(function(a){a._pure=function(a,c){return function(e,d){try{e(c)}catch(f){d(f)}return a}};a._throwError=function(a,c){return function(e,d){d(c);return a}};a._fmap=function(a,c){return function(e,d){return c(function(c){try{e(a(c))}catch(g){d(g)}},d)}};a._bind=function(a,c,e){return function(d,f){var g,l,h=!1,m=!1,k=function(){};g=c(function(c){if(m)return h=!0,a;l=e(c)(d,f);k(l);return l},f);return function(a){return function(b,c){m=!0;return void 0!==l?l(a)(b,c):g(a)(function(d){if(d||h)try{b(!0)}catch(e){c(e)}else k=
function(d){d(a)(b,c)}},c)}}}};a._attempt=function(a,c,e){return function(d,f){return e(function(a){try{d(c(a))}catch(b){f(b)}},function(c){try{d(a(c))}catch(e){f(e)}})}};a._runAff=function(a,c,e){return function(){return e(function(d){try{c(d)()}catch(e){a(e)()}},function(c){a(c)()})}};a._liftEff=function(a,c){return function(e,d){try{e(c())}catch(f){d(f)}return a}}})(PS["Control.Monad.Aff"]=PS["Control.Monad.Aff"]||{});
(function(a){a.returnE=function(a){return function(){return a}};a.bindE=function(a){return function(c){return function(){return c(a())()}}};a.runPure=function(a){return a()}})(PS["Control.Monad.Eff"]=PS["Control.Monad.Eff"]||{});
(function(a){var b=PS["Control.Monad.Eff"],c=PS.Prelude,e=new c.Monad(function(){return g},function(){return d}),d=new c.Bind(function(){return f},b.bindE),f=new c.Apply(function(){return l},c.ap(e)),g=new c.Applicative(function(){return f},b.returnE),l=new c.Functor(c.liftA1(g));a.functorEff=l;a.applyEff=f;a.applicativeEff=g;a.bindEff=d;a.monadEff=e;a.runPure=b.runPure})(PS["Control.Monad.Eff"]=PS["Control.Monad.Eff"]||{});
(function(a){a.MonadEff=function(a,c){this["__superclass_Prelude.Monad_0"]=a;this.liftEff=c};a.liftEff=function(a){return a.liftEff}})(PS["Control.Monad.Eff.Class"]=PS["Control.Monad.Eff.Class"]||{});(function(a){a.showErrorImpl=function(a){return a.stack||a.toString()};a.error=function(a){return Error(a)};a.message=function(a){return a.message}})(PS["Control.Monad.Eff.Exception"]=PS["Control.Monad.Eff.Exception"]||{});
(function(a){var b=PS["Control.Monad.Eff.Exception"],c=new PS.Prelude.Show(b.showErrorImpl);a.showError=c;a.message=b.message;a.error=b.error})(PS["Control.Monad.Eff.Exception"]=PS["Control.Monad.Eff.Exception"]||{});(function(a){a.mempty=function(a){return a.mempty}})(PS["Data.Monoid"]=PS["Data.Monoid"]||{});
(function(a){var b=PS.Prelude,c=function(){function a(){}a.value=new a;return a}(),e=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),d=new b.Functor(function(a){return function(b){return b instanceof e?new e(a(b.value0)):c.value}}),f=new b.Apply(function(){return d},function(a){return function(g){if(a instanceof e)return b["<$>"](d)(a.value0)(g);if(a instanceof c)return c.value;throw Error("Failed pattern match at Data.Maybe line 121, column 1 - line 145, column 1: "+
[a.constructor.name,g.constructor.name]);}}),g=new b.Bind(function(){return f},function(a){return function(b){if(a instanceof e)return b(a.value0);if(a instanceof c)return c.value;throw Error("Failed pattern match at Data.Maybe line 180, column 1 - line 199, column 1: "+[a.constructor.name,b.constructor.name]);}}),l=new b.Applicative(function(){return f},e.create);a.Nothing=c;a.Just=e;a.maybe=function(a){return function(b){return function(d){if(d instanceof c)return a;if(d instanceof e)return b(d.value0);
throw Error("Failed pattern match at Data.Maybe line 26, column 1 - line 27, column 1: "+[a.constructor.name,b.constructor.name,d.constructor.name]);}}};a.functorMaybe=d;a.applyMaybe=f;a.applicativeMaybe=l;a.bindMaybe=g})(PS["Data.Maybe"]=PS["Data.Maybe"]||{});
(function(a){a.foldrArray=function(a){return function(c){return function(e){for(var d=c,f=e.length-1;0<=f;f--)d=a(e[f])(d);return d}}};a.foldlArray=function(a){return function(c){return function(e){for(var d=c,f=e.length,g=0;g<f;g++)d=a(d)(e[g]);return d}}}})(PS["Data.Foldable"]=PS["Data.Foldable"]||{});
(function(a){var b=PS["Data.Foldable"],c=PS.Prelude,e=PS["Data.Maybe"],d=PS["Data.Monoid"],f=function(a,b,c){this.foldMap=a;this.foldl=b;this.foldr=c},g=new f(function(a){return function(b){return function(e){return(0,g.foldr)(function(d){return function(e){return c["<>"](a["__superclass_Prelude.Semigroup_0"]())(b(d))(e)}})(d.mempty(a))(e)}}},b.foldlArray,b.foldrArray);a.Foldable=f;a.find=function(a){return function(b){return(0,a.foldl)(function(a){return function(c){var d=b(c);if(d)return new e.Just(c);
if(!d)return a;throw Error("Failed pattern match at Data.Foldable line 181, column 1 - line 182, column 1: "+[d.constructor.name]);}})(e.Nothing.value)}};a.foldMap=function(a){return a.foldMap};a.foldl=function(a){return a.foldl};a.foldr=function(a){return a.foldr};a.foldableArray=g})(PS["Data.Foldable"]=PS["Data.Foldable"]||{});
(function(a){a.traverseArrayImpl=function(){function a(b){this.fn=b}function c(a){return function(b){return new f(a,b)}}function e(a){for(var b=[];a!==d;)b.push(a.head),a=a.tail;return b}var d={},f=function(a,b){this.head=a;this.tail=b};return function(g){return function(f){return function(h){return function(m){var k=function(d,e,h){if(0===e)return d;var q=h[e-1];return new a(function(){var a=k,b;b=g(f(c)(m(q)))(d);return a(b,e-1,h)})};return function(c){for(c=k(h(d),c.length,c);c instanceof a;)c=
c.fn();return f(e)(c)}}}}}}()})(PS["Data.Traversable"]=PS["Data.Traversable"]||{});
(function(a){var b=PS["Data.Traversable"],c=PS.Prelude,e=PS["Data.Foldable"],d=function(a,b,c,d){this["__superclass_Data.Foldable.Foldable_1"]=a;this["__superclass_Prelude.Functor_0"]=b;this.sequence=c;this.traverse=d},f=new d(function(){return e.foldableArray},function(){return c.functorArray},function(a){return(0,f.traverse)(a)(c.id(c.categoryFn))},function(a){return b.traverseArrayImpl(c.apply(a["__superclass_Prelude.Apply_0"]()))(c.map(a["__superclass_Prelude.Apply_0"]()["__superclass_Prelude.Functor_0"]()))(c.pure(a))});a.Traversable=
d;a["for"]=function(a){return function(b){return function(c){return function(d){return(0,b.traverse)(a)(d)(c)}}}};a.sequence=function(a){return a.sequence};a.traverse=function(a){return a.traverse};a.traversableArray=f})(PS["Data.Traversable"]=PS["Data.Traversable"]||{});
(function(a){var b=PS.Prelude,c=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),e=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),d=new b.Functor(function(a){return function(b){if(b instanceof c)return new c(b.value0);if(b instanceof e)return new e(a(b.value0));throw Error("Failed pattern match at Data.Either line 52, column 1 - line 56, column 1: "+[a.constructor.name,b.constructor.name]);}}),f=function(a){return function(b){return function(d){if(d instanceof
c)return a(d.value0);if(d instanceof e)return b(d.value0);throw Error("Failed pattern match at Data.Either line 28, column 1 - line 29, column 1: "+[a.constructor.name,b.constructor.name,d.constructor.name]);}}},g=new b.Apply(function(){return d},function(a){return function(f){if(a instanceof c)return new c(a.value0);if(a instanceof e)return b["<$>"](d)(a.value0)(f);throw Error("Failed pattern match at Data.Either line 92, column 1 - line 116, column 1: "+[a.constructor.name,f.constructor.name]);
}}),l=new b.Bind(function(){return g},f(function(a){return function(b){return new c(a)}})(function(a){return function(b){return b(a)}})),h=new b.Applicative(function(){return g},e.create);a.Left=c;a.Right=e;a.either=f;a.functorEither=d;a.applyEither=g;a.applicativeEither=h;a.bindEither=l})(PS["Data.Either"]=PS["Data.Either"]||{});
(function(a){a.MonadError=function(a,c,e){this["__superclass_Prelude.Monad_0"]=a;this.catchError=c;this.throwError=e};a.catchError=function(a){return a.catchError};a.throwError=function(a){return a.throwError}})(PS["Control.Monad.Error.Class"]=PS["Control.Monad.Error.Class"]||{});(function(a){a.runFn4=function(a){return function(c){return function(e){return function(d){return function(f){return a(c,e,d,f)}}}}}})(PS["Data.Function"]=PS["Data.Function"]||{});
(function(a){a.runFn4=PS["Data.Function"].runFn4})(PS["Data.Function"]=PS["Data.Function"]||{});
(function(a){var b=PS["Control.Monad.Aff"],c=PS.Prelude,e=PS["Control.Monad.Eff.Class"],d=PS["Control.Monad.Error.Class"],f=PS["Data.Either"],g=new c.Functor(function(a){return function(c){return b._fmap(a,c)}}),l=function(a){return b._attempt(f.Left.create,f.Right.create,a)},h=new c.Apply(function(){return g},function(a){return function(d){return b._bind(r,a,function(a){return c["<$>"](g)(a)(d)})}}),m=new c.Applicative(function(){return h},function(a){return b._pure(k,a)}),k=c["const"](c.pure(m)(!1)),
r=c["const"](c.pure(m)(!0)),n=new c.Bind(function(){return h},function(a){return function(c){return b._bind(r,a,c)}}),p=new c.Monad(function(){return m},function(){return n}),e=new e.MonadEff(function(){return p},function(a){return b._liftEff(k,a)}),q=new d.MonadError(function(){return p},function(a){return function(b){return c[">>="](n)(l(a))(f.either(b)(c.pure(m)))}},function(a){return b._throwError(k,a)});a.runAff=function(a){return function(c){return function(d){return b._runAff(a,c,d)}}};a.nonCanceler=
k;a["finally"]=function(a){return function(b){return c.bind(n)(l(a))(function(a){return c.bind(n)(b)(function(){return f.either(d.throwError(q))(c.pure(m))(a)})})}};a.attempt=l;a.functorAff=g;a.applyAff=h;a.applicativeAff=m;a.bindAff=n;a.monadAff=p;a.monadEffAff=e;a.monadErrorAff=q})(PS["Control.Monad.Aff"]=PS["Control.Monad.Aff"]||{});(function(a){a.log=function(a){return function(){console.log(a);return{}}}})(PS["Control.Monad.Eff.Console"]=PS["Control.Monad.Eff.Console"]||{});
(function(a){a.log=PS["Control.Monad.Eff.Console"].log})(PS["Control.Monad.Eff.Console"]=PS["Control.Monad.Eff.Console"]||{});
(function(a){function b(a){return a}a.fromBoolean=b;a.fromNumber=b;a.fromString=b;a.fromArray=b;a.fromObject=b;a.jsonNull=null;a._stringify=function(a){return JSON.stringify(a)};a._foldJson=function(a,b,d,f,g,l,h){return null==h?a(null):"boolean"===typeof h?b(h):"number"===typeof h?d(h):"string"===typeof h?f(h):"[object Array]"===Object.prototype.toString.call(h)?g(h):l(h)}})(PS["Data.Argonaut.Core"]=PS["Data.Argonaut.Core"]||{});
(function(a){a._copyEff=function(a){return function(){var c={},e;for(e in a)a.hasOwnProperty(e)&&(c[e]=a[e]);return c}};a.empty={};a.runST=function(a){return a};a._lookup=function(a,c,e,d){return e in d?c(d[e]):a}})(PS["Data.StrMap"]=PS["Data.StrMap"]||{});(function(a){a["new"]=function(){return{}};a.poke=function(a){return function(c){return function(e){return function(){a[c]=e;return a}}}}})(PS["Data.StrMap.ST"]=PS["Data.StrMap.ST"]||{});
(function(a){var b=PS["Data.StrMap.ST"];a.poke=b.poke;a["new"]=b["new"]})(PS["Data.StrMap.ST"]=PS["Data.StrMap.ST"]||{});
(function(a){var b=PS["Data.StrMap"],c=PS.Prelude,e=PS["Control.Monad.Eff"],d=PS["Data.Maybe"],f=PS["Data.StrMap.ST"],g=b._copyEff,l=function(a){return e.runPure(b.runST(a))},h=function(a){return function(b){return l(function(){var d=g(b)();a(d)();return c["return"](e.applicativeEff)(d)()})}},d=PS["Data.Function"].runFn4(b._lookup)(d.Nothing.value)(d.Just.create);a.thawST=g;a.lookup=d;a.insert=function(a){return function(b){return h(function(c){return f.poke(c)(a)(b)})}};a.singleton=function(a){return function(b){return l(function(){var d=
f["new"]();f.poke(d)(a)(b)();return c["return"](e.applicativeEff)(d)()})}};a.empty=b.empty})(PS["Data.StrMap"]=PS["Data.StrMap"]||{});
(function(a){var b=PS["Data.Argonaut.Core"],c=PS.Prelude,e=PS["Data.Maybe"],d=function(a){return function(b){return function(c){return c(a)(b)}}}(e.Nothing.value)(e.Just.create),e=new c.Show(b._stringify),f=function(a){return function(d){return function(e){return b._foldJson(c["const"](a),c["const"](a),c["const"](a),d,c["const"](a),c["const"](a),e)}}},g=d(f),l=function(a){return function(d){return function(e){return b._foldJson(c["const"](a),c["const"](a),c["const"](a),c["const"](a),c["const"](a),
d,e)}}},h=d(l),m=function(a){return function(d){return function(e){return b._foldJson(c["const"](a),c["const"](a),d,c["const"](a),c["const"](a),c["const"](a),e)}}},k=d(m),r=function(a){return function(d){return function(e){return b._foldJson(c["const"](a),d,c["const"](a),c["const"](a),c["const"](a),c["const"](a),e)}}},n=d(r),p=function(a){return function(d){return function(e){return b._foldJson(c["const"](a),c["const"](a),c["const"](a),c["const"](a),d,c["const"](a),e)}}},d=d(p);a.toObject=h;a.toArray=
d;a.toString=g;a.toNumber=k;a.toBoolean=n;a.foldJsonObject=l;a.foldJsonArray=p;a.foldJsonString=f;a.foldJsonNumber=m;a.foldJsonBoolean=r;a.foldJsonNull=function(a){return function(d){return function(e){return b._foldJson(d,c["const"](a),c["const"](a),c["const"](a),c["const"](a),c["const"](a),e)}}};a.showJson=e;a.jsonNull=b.jsonNull;a.fromObject=b.fromObject;a.fromArray=b.fromArray;a.fromString=b.fromString;a.fromNumber=b.fromNumber;a.fromBoolean=b.fromBoolean})(PS["Data.Argonaut.Core"]=PS["Data.Argonaut.Core"]||
{});(function(a){a.length=function(a){return a.length};a.zipWith=function(a){return function(c){return function(e){for(var d=c.length<e.length?c.length:e.length,f=Array(d),g=0;g<d;g++)f[g]=a(c[g])(e[g]);return f}}}})(PS["Data.Array"]=PS["Data.Array"]||{});(function(a){var b=PS["Data.Array"],c=PS["Data.Traversable"];a.zipWithA=function(a){return function(d){return function(f){return function(g){return c.sequence(c.traversableArray)(a)(b.zipWith(d)(f)(g))}}}}})(PS["Data.Array"]=PS["Data.Array"]||{});
(function(a){a.fromNumberImpl=function(a){return function(c){return function(e){return(e|0)===e?a(e):c}}};a.toNumber=function(a){return a}})(PS["Data.Int"]=PS["Data.Int"]||{});(function(a){var b=PS["Data.Int"],c=PS["Data.Maybe"],c=b.fromNumberImpl(c.Just.create)(c.Nothing.value);a.fromNumber=c;a.toNumber=b.toNumber})(PS["Data.Int"]=PS["Data.Int"]||{});(function(a){a.joinWith=function(a){return function(c){return c.join(a)}}})(PS["Data.String"]=PS["Data.String"]||{});
(function(a){a.joinWith=PS["Data.String"].joinWith})(PS["Data.String"]=PS["Data.String"]||{});
(function(a){var b=PS["Data.Maybe"],c=function(){function a(){}a.value=new a;return a}(),e=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),d=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),f=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),g=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),l=function(){function a(b){this.value0=
b}a.create=function(b){return new a(b)};return a}(),h=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),m=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),k=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),r=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),n=function(){function a(){}a.value=new a;return a}(),p=function(){function a(){}a.value=
new a;return a}(),q=function(){function a(){}a.value=new a;return a}(),t=function(){function a(){}a.value=new a;return a}(),u=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),v=function(a,b,c){this.fromSpine=a;this.toSignature=b;this.toSpine=c},x=new v(function(a){return a instanceof h?new b.Just(a.value0):b.Nothing.value},function(a){return t.value},function(a){return new h(a)}),y=c.value;a.Proxy=c;a.SigProd=k;a.SigRecord=r;a.SigNumber=n;a.SigBoolean=p;a.SigInt=
q;a.SigString=t;a.SigArray=u;a.SProd=e;a.SRecord=d;a.SNumber=f;a.SBoolean=g;a.SInt=l;a.SString=h;a.SArray=m;a.Generic=v;a.anyProxy=y;a.fromSpine=function(a){return a.fromSpine};a.toSignature=function(a){return a.toSignature};a.toSpine=function(a){return a.toSpine};a.genericString=x})(PS["Data.Generic"]=PS["Data.Generic"]||{});
(function(a){var b=PS.Prelude,c=PS["Data.Argonaut.Core"],e=PS["Data.Array"],d=PS["Data.Either"],f=PS["Data.Int"],g=PS["Data.Maybe"],l=PS["Control.Bind"],h=PS["Data.Traversable"],m=PS["Data.Foldable"],k=PS["Data.Generic"],r=PS["Data.StrMap"],n=function(a){this.decodeJson=a},p=function(a){return function(q){var n=function(a){return g.maybe(new d.Left(a))(d.Right.create)};if(a instanceof k.SigNumber)return b["<$>"](d.functorEither)(k.SNumber.create)(n("Expected a number")(c.toNumber(q)));if(a instanceof
k.SigInt)return b["<$>"](d.functorEither)(k.SInt.create)(n("Expected an integer number")(l["=<<"](g.bindMaybe)(f.fromNumber)(c.toNumber(q))));if(a instanceof k.SigString)return b["<$>"](d.functorEither)(k.SString.create)(n("Expected a string")(c.toString(q)));if(a instanceof k.SigBoolean)return b["<$>"](d.functorEither)(k.SBoolean.create)(n("Expected a boolean")(c.toBoolean(q)));if(a instanceof k.SigArray)return b.bind(d.bindEither)(n("Expected an array")(c.toArray(q)))(function(c){return b["<$>"](d.functorEither)(k.SArray.create)(h.traverse(h.traversableArray)(d.applicativeEither)(function(c){return b.map(d.functorEither)(b["const"])(p(a.value0(b.unit))(c))})(c))});
if(a instanceof k.SigRecord)return b.bind(d.bindEither)(n("Expected an object")(c.toObject(q)))(function(c){return b["<$>"](d.functorEither)(k.SRecord.create)(h["for"](d.applicativeEither)(h.traversableArray)(a.value0)(function(a){return b.bind(d.bindEither)(n("'"+(a.recLabel+"' property missing"))(r.lookup(a.recLabel)(c)))(function(c){return b.bind(d.bindEither)(p(a.recValue(b.unit))(c))(function(c){return b.pure(d.applicativeEither)({recLabel:a.recLabel,recValue:b["const"](c)})})})}))});if(a instanceof
k.SigProd)return b.bind(d.bindEither)(n("Expected an object")(c.toObject(q)))(function(f){return b.bind(d.bindEither)(n("'tag' string property is missing")(l["=<<"](g.bindMaybe)(c.toString)(r.lookup("tag")(f))))(function(h){var q=m.find(m.foldableArray)(function(a){return b["=="](b.eqString)(h)(a.sigConstructor)})(a.value0);if(q instanceof g.Nothing)return new d.Left("'"+(h+"' isn't a valid constructor"));if(q instanceof g.Just)return b.bind(d.bindEither)(n("'values' array is missing")(l["=<<"](g.bindMaybe)(c.toArray)(r.lookup("values")(f))))(function(a){return b.bind(d.bindEither)(e.zipWithA(d.applicativeEither)(function(a){return p(a(b.unit))})(q.value0.sigValues)(a))(function(a){return b.pure(d.applicativeEither)(new k.SProd(h,
b["<$>"](b.functorArray)(b["const"])(a)))})});throw Error("Failed pattern match: "+[q.constructor.name]);})});throw Error("Failed pattern match: "+[a.constructor.name]);}},q=new n(c.foldJsonNull(new d.Left("Not null."))(b["const"](new d.Right(b.unit)))),t=function(a){return function(c){return d.either(b["const"](g.Nothing.value))(b.pure(g.applicativeMaybe))((0,a.decodeJson)(c))}};a.DecodeJson=n;a.decodeMaybe=t;a.gDecodeJson=function(a){return function(b){return l["=<<"](d.bindEither)(function(b){return g.maybe(new d.Left("fromSpine failed"))(d.Right.create)(k.fromSpine(a)(b))})(p(k.toSignature(a)(k.Proxy.value))(b))}};
a.decodeJson=function(a){return a.decodeJson};a.decodeJsonNull=q;a.decodeArray=function(a){return new n(function(e){return g.maybe(new d.Left("Couldn't decode."))(d.Right.create)(b.bind(g.bindMaybe)(c.toArray(e))(function(b){return h.traverse(h.traversableArray)(g.applicativeMaybe)(t(a))(b)}))})}})(PS["Data.Argonaut.Decode"]=PS["Data.Argonaut.Decode"]||{});
(function(a){var b=PS.Prelude,c=PS["Data.Argonaut.Core"],e=PS["Data.Int"],d=PS["Data.Foldable"],f=PS["Data.Generic"],g=PS["Data.StrMap"],l=function(a){this.encodeJson=a},h=new l(b["const"](c.jsonNull)),m=new l(b.id(b.categoryFn)),k=new l(c.fromString),r=function(a){return a.encodeJson},n=function(a){return new l(function(d){return c.fromArray(b["<$>"](b.functorArray)(a.encodeJson)(d))})},p=function(a){var h=function(a){return g.insert(a.recLabel)(p(a.recValue(b.unit)))};if(a instanceof f.SInt)return c.fromNumber(e.toNumber(a.value0));
if(a instanceof f.SString)return c.fromString(a.value0);if(a instanceof f.SNumber)return c.fromNumber(a.value0);if(a instanceof f.SBoolean)return c.fromBoolean(a.value0);if(a instanceof f.SArray)return c.fromArray(b["<$>"](b.functorArray)(function(a){return p(a(b.unit))})(a.value0));if(a instanceof f.SProd)return c.fromObject(g.insert("tag")((0,k.encodeJson)(a.value0))(g.singleton("values")(r(n(m))(b["<$>"](b.functorArray)(function(a){return p(a(b.unit))})(a.value1)))));if(a instanceof f.SRecord)return c.fromObject(d.foldr(d.foldableArray)(h)(g.empty)(a.value0));
throw Error("Failed pattern match: "+[a.constructor.name]);};a.EncodeJson=l;a.gEncodeJson=function(a){return function(b){return p(f.toSpine(a)(b))}};a.encodeJson=r;a.encodeJsonUnit=h;a.encodeJsonJString=k;a.encodeJsonJson=m;a.encodeJsonArray=n})(PS["Data.Argonaut.Encode"]=PS["Data.Argonaut.Encode"]||{});
(function(a){var b=function(a){this.printJson=a},c=new b(PS.Prelude.show(PS["Data.Argonaut.Core"].showJson));a.Printer=b;a.printJson=function(a){return a.printJson};a.printerString=c})(PS["Data.Argonaut.Printer"]=PS["Data.Argonaut.Printer"]||{});
(function(a){a.unsafeFromForeign=function(a){return a};a.typeOf=function(a){return typeof a};a.tagOf=function(a){return Object.prototype.toString.call(a).slice(8,-1)};a.isNull=function(a){return null===a};a.isUndefined=function(a){return void 0===a}})(PS["Data.Foreign"]=PS["Data.Foreign"]||{});
(function(a){var b=PS["Data.Foreign"],c=PS.Prelude,e=PS["Data.Either"],d=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),f=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),g=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),l=function(){function a(b){this.value0=b}a.create=
function(b){return new a(b)};return a}(),h=function(a){return function(f){return c["=="](c.eqString)(b.tagOf(f))(a)?c.pure(e.applicativeEither)(b.unsafeFromForeign(f)):new e.Left(new d(a,b.tagOf(f)))}},m=new c.Show(function(a){if(a instanceof d)return"Type mismatch: expected "+(a.value0+(", found "+a.value1));if(a instanceof f)return"Error at array index "+(c.show(c.showInt)(a.value0)+(": "+c.show(m)(a.value1)));if(a instanceof g)return"Error at property "+(c.show(c.showString)(a.value0)+(": "+c.show(m)(a.value1)));
if(a instanceof l)return"JSON error: "+a.value0;throw Error("Failed pattern match: "+[a.constructor.name]);}),k=h("String");a.TypeMismatch=d;a.ErrorAtIndex=f;a.ErrorAtProperty=g;a.JSONError=l;a.readString=k;a.unsafeReadTagged=h;a.showForeignError=m;a.isUndefined=b.isUndefined;a.isNull=b.isNull;a.typeOf=b.typeOf})(PS["Data.Foreign"]=PS["Data.Foreign"]||{});
(function(a){a.unsafeReadPropImpl=function(a,c,e,d){return null==d?a:c(d[e])};a.unsafeHasOwnProperty=function(a,c){return Object.prototype.hasOwnProperty.call(c,a)};a.unsafeHasProperty=function(a,c){return a in c}})(PS["Data.Foreign.Index"]=PS["Data.Foreign.Index"]||{});
(function(a){var b=PS["Data.Foreign.Index"],c=PS.Prelude,e=PS["Data.Either"],d=PS["Data.Foreign"],f=function(a,b,c,d){this.errorAt=a;this.hasOwnProperty=b;this.hasProperty=c;this.ix=d},g=function(a){return function(f){return b.unsafeReadPropImpl(new e.Left(new d.TypeMismatch("object",d.typeOf(f))),c.pure(e.applicativeEither),a,f)}},l=new f(d.ErrorAtProperty.create,function(a){return function(e){return d.isNull(e)||d.isUndefined(e)?!1:c["=="](c.eqString)(d.typeOf(e))("object")||c["=="](c.eqString)(d.typeOf(e))("function")?
b.unsafeHasOwnProperty(a,e):!1}},function(a){return function(e){return d.isNull(e)||d.isUndefined(e)?!1:c["=="](c.eqString)(d.typeOf(e))("object")||c["=="](c.eqString)(d.typeOf(e))("function")?b.unsafeHasProperty(a,e):!1}},c.flip(g));a.Index=f;a.errorAt=function(a){return a.errorAt};a.hasOwnProperty=function(a){return a.hasOwnProperty};a.hasProperty=function(a){return a.hasProperty};a["!"]=function(a){return a.ix};a.ix=function(a){return a.ix};a.prop=g;a.indexString=l})(PS["Data.Foreign.Index"]=PS["Data.Foreign.Index"]||
{});
(function(a){var b=PS.Prelude,c=PS["Data.Either"],e=PS["Data.Foreign.Index"],d=function(a){this.read=a},f=new d(PS["Data.Foreign"].readString),g=function(a){return function(b){return function(d){return c.either(function(a){return c.Left.create(b(a))})(c.Right.create)((0,a.read)(d))}}};a.IsForeign=d;a.readProp=function(a){return function(d){return function(f){return function(k){return b[">>="](c.bindEither)(e["!"](d)(k)(f))(g(a)(e.errorAt(d)(f)))}}}};a.readWith=g;a.read=function(a){return a.read};a.stringIsForeign=
f})(PS["Data.Foreign.Class"]=PS["Data.Foreign.Class"]||{});(function(a){a.connect_=function(a){return function(c,e){require("any-db").createConnection(a,function(a,b){a?e(a):c(b)})}};a.runQuery_=function(a){return function(c){return function(e,d){c.query(a,function(a,b){a?d(a):e(b.rows)})}}};a.close=function(a){return function(){a.end()}}})(PS["Database.AnyDB"]=PS["Database.AnyDB"]||{});
(function(a){var b=PS["Database.AnyDB"],c=PS.Prelude,e=PS["Data.Either"],d=PS["Data.Foreign"],f=PS["Data.Foreign.Class"],g=PS["Control.Monad.Aff"],l=PS["Control.Monad.Eff.Class"],h=PS["Control.Monad.Eff.Exception"],m=PS["Control.Monad.Error.Class"],k=PS["Data.Traversable"],r=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),n=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),p=function(a){if(a instanceof r)return"postgres://"+
(a.value0.user+(":"+(a.value0.password+("@"+(a.value0.host+(":"+(c.show(c.showInt)(a.value0.port)+("/"+a.value0.db))))))));if(a instanceof n){if(a.value0.memory)a=":memory:";else{if(a.value0.memory)throw Error("Failed pattern match at Database.AnyDB line 64, column 1 - line 65, column 1: "+[a.value0.memory.constructor.name]);a=a.value0.filename}return"sqlite3://"+a}throw Error("Failed pattern match at Database.AnyDB line 64, column 1 - line 65, column 1: "+[a.constructor.name]);},q=function(a){return m.throwError(g.monadErrorAff)(h.error(c.show(d.showForeignError)(a)))},
t=function(a){return b.connect_(p(a))};a.Postgres=r;a.Sqlite3=n;a.Query=function(a){return a};a.withConnection=function(a){return function(d){return c.bind(g.bindAff)(t(a))(function(a){return g["finally"](d(a))(l.liftEff(g.monadEffAff)(b.close(a)))})}};a.query_=function(a){return function(d){return function(h){return c.bind(g.bindAff)(b.runQuery_(d)(h))(function(b){return e.either(q)(c.pure(g.applicativeAff))(k.sequence(k.traversableArray)(e.applicativeEither)(c["<$>"](c.functorArray)(f.read(a))(b)))})}}};
a.execute_=function(a){return function(d){return c["void"](g.functorAff)(b.runQuery_(a)(d))}};a.connect=t;a.mkConnectionString=p})(PS["Database.AnyDB"]=PS["Database.AnyDB"]||{});(function(a){var b=function(){function a(){}a.value=new a;return a}(),c=function(){function a(){}a.value=new a;return a}(),e=function(){function a(){}a.value=new a;return a}();a.GET=b;a.POST=c;a.PUT=e})(PS["Network.HTTP.Method"]=PS["Network.HTTP.Method"]||{});
(function(a){var b=PS.Prelude,c=PS["Data.String"],e=PS["Database.AnyDB"],d=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),f=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),g=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),l=new b.Show(function(a){return a.value0}),h=new b.Show(function(a){return"CHAR("+(b.show(b.showInt)(a.value0)+")")}),
m=new b.Show(function(a){return a.value0+(" "+b.show(h)(a.value1))});a.Char=f;a.FieldDef=g;a.Table=d;a.selectStar=function(a){return function(b){return e.Query("SELECT * FROM "+(a.value0+(" "+b)))}};a.insert=function(a){return function(d){return e.Query("INSERT INTO "+(a.value0+(" VALUES ("+(c.joinWith(", ")(b.map(b.functorArray)(function(a){return"'"+(a+"'")})(d))+")"))))}};a.createTable=function(a){return function(d){return e.Query("CREATE TABLE "+(a.value0+(" ("+(c.joinWith(", ")(b.map(b.functorArray)(b.show(m))(d))+
")"))))}};a.dropTable=function(a){return e.Query("DROP TABLE IF EXISTS "+a.value0)};a.showTable=l;a.showFieldDef=m;a.showFieldType=h})(PS["Klikhut.SQL"]=PS["Klikhut.SQL"]||{});
(function(a){var b=PS.Prelude,c=PS["Klikhut.SQL"],e=PS["Data.Foreign.Class"],d=PS["Data.Generic"],f=PS["Data.Argonaut.Encode"],g=PS["Data.Argonaut.Decode"],l=PS["Data.Maybe"],h=PS["Data.Either"],m=PS["Data.Foreign.Index"],k=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),r=new c.Table("PHOTOBOOTHS"),n=new e.IsForeign(function(a){return b.bind(h.bindEither)(e.readProp(e.stringIsForeign)(m.indexString)("computername")(a))(function(c){return b.bind(h.bindEither)(e.readProp(e.stringIsForeign)(m.indexString)("alias")(a))(function(d){return b.bind(h.bindEither)(e.readProp(e.stringIsForeign)(m.indexString)("defaultprofile")(a))(function(a){return b["return"](h.applicativeEither)(new k({computername:c,
alias:d,defaultprofile:a}))})})})}),p=new d.Generic(function(a){return a instanceof d.SProd&&"Photobooth"===a.value0&&1===a.value1.length?b.apply(l.applyMaybe)(new l.Just(k.create))(function(a){return a instanceof d.SRecord&&3===a.value0.length?b.apply(l.applyMaybe)(b.apply(l.applyMaybe)(b.apply(l.applyMaybe)(new l.Just(function(a){return function(b){return function(c){return{alias:a,computername:b,defaultprofile:c}}}}))(d.fromSpine(d.genericString)(a.value0[0].recValue(b.unit))))(d.fromSpine(d.genericString)(a.value0[1].recValue(b.unit))))(d.fromSpine(d.genericString)(a.value0[2].recValue(b.unit))):
l.Nothing.value}(a.value1[0](b.unit))):l.Nothing.value},function(a){return new d.SigProd([{sigConstructor:"Photobooth",sigValues:[function(a){return new d.SigRecord([{recLabel:"alias",recValue:function(a){return d.toSignature(d.genericString)(d.anyProxy)}},{recLabel:"computername",recValue:function(a){return d.toSignature(d.genericString)(d.anyProxy)}},{recLabel:"defaultprofile",recValue:function(a){return d.toSignature(d.genericString)(d.anyProxy)}}])}]}])},function(a){return new d.SProd("Photobooth",
[function(b){return new d.SRecord([{recLabel:"alias",recValue:function(b){return d.toSpine(d.genericString)(a.value0.alias)}},{recLabel:"computername",recValue:function(b){return d.toSpine(d.genericString)(a.value0.computername)}},{recLabel:"defaultprofile",recValue:function(b){return d.toSpine(d.genericString)(a.value0.defaultprofile)}}])}])}),f=new f.EncodeJson(f.gEncodeJson(p)),g=new g.DecodeJson(g.gDecodeJson(p)),c=[c.FieldDef.create("computername")(new c.Char(50)),c.FieldDef.create("alias")(new c.Char(50)),
c.FieldDef.create("defaultprofile")(new c.Char(50))];a.Photobooth=k;a.cols=c;a.table=r;a.genericPhotobooth=p;a.encodeJsonPhotobooth=f;a.decodeJsonPhotobooth=g;a.photoboothIsForeign=n})(PS["Klikhut.Model.Photobooth"]=PS["Klikhut.Model.Photobooth"]||{});
(function(a){var b=PS.Prelude,c=PS["Network.HTTP.Method"],e=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),d=new e({method:c.PUT.value,serverUrl:"/api/photobooths",mkClientUrl:b["const"]("/api/photobooths")}),f=new e({method:c.POST.value,serverUrl:"/api/photobooths",mkClientUrl:b["const"]("/api/photobooths")}),b=new e({method:c.GET.value,serverUrl:"/api/photobooths",mkClientUrl:b["const"]("/api/photobooths")});a.Endpoint=e;a.putPhotobooths=d;a.postPhotobooths=
f;a.getPhotobooths=b})(PS["Klikhut.Endpoint"]=PS["Klikhut.Endpoint"]||{});
(function(a){a.makeApp=function(){var a=require("express")(),c=require("body-parser");a.use(c.json());return a};a.listen=function(a){return function(c){return function(){var e=require("http").createServer(a);e.listen(c);return e}}};a.get=function(a){return function(c){return function(e){return function(){a.get(c,function(a,b){return e(a)(b)()})}}}};a.post=function(a){return function(c){return function(e){return function(){a.post(c,function(a,b){return e(a)(b)()})}}}};a.put=function(a){return function(c){return function(e){return function(){a.put(c,
function(a,b){return e(a)(b)()})}}}};a.mkConvert=function(a){return function(c){return a(c.url)(c.body&&0!==Object.keys(c.body).length?c.body:null)(c.params)(c.path)(c.query)(c.headers)}};a.sendStr=function(a){return function(c){return function(){a.send(c)}}};a.sendFile=function(a){return function(c){return function(){a.sendFile(c,{root:process.cwd()})}}}})(PS["Klikhut.Server.Core"]=PS["Klikhut.Server.Core"]||{});
(function(a){var b=PS["Klikhut.Server.Core"],c=PS.Prelude,e=PS["Data.Argonaut.Decode"],d=PS["Data.Argonaut.Encode"],f=PS["Data.Argonaut.Printer"],g=PS["Control.Monad.Aff"],l=PS["Network.HTTP.Method"],h=PS["Control.Monad.Eff.Exception"],m=PS["Control.Monad.Error.Class"],k=PS["Data.Either"],r=PS["Control.Monad.Eff.Console"],n=function(a){return function(b){return k.either(function(a){return m.throwError(g.monadErrorAff)(h.error("failed to parse input: "+a))})(function(a){var d=c["return"](g.applicativeAff),
e={},f;for(f in b)b.hasOwnProperty(f)&&(e[f]=b[f]);e.body=a;return d(e)})(e.decodeJson(a)(b.body))}},p=b.mkConvert(function(a){return function(b){return function(c){return function(d){return function(e){return function(f){return{url:a,body:b,params:c,path:d,query:e,headers:f}}}}}}});a.hostFile=function(a){return function(d){return function(f){return b.get(a)(d)(function(a){return function(d){return g.runAff(function(a){return function(){r.log("Failed hostFile "+h.message(a))();return b.sendStr(d)(h.message(a))()}})(function(a){return b.sendFile(d)(a)})(c[">>="](g.bindAff)(n(e.decodeJsonNull)(p(a)))(f))}})}}};
a.hostEndpoint=function(a){return function(a){return function(e){return function(k){return function(k){return function(m){return function(q){if(m.value0.method instanceof l.GET){var w=function(l){return function(k){return g.runAff(function(a){return function(){r.log("Failed hostEndpoint GET on "+(m.value0.serverUrl+h.message(a)))();return b.sendStr(k)(h.message(a))()}})(function(a){return b.sendStr(k)(f.printJson(f.printerString)(d.encodeJson(e)(a)))})(c[">>="](g.bindAff)(n(a)(p(l)))(q))}};return b.get(k)(m.value0.serverUrl)(w)}if(m.value0.method instanceof
l.POST)return w=function(l){return function(k){return g.runAff(function(a){return function(){r.log("Failed hostEndpoint POST on "+(m.value0.serverUrl+h.message(a)))();return b.sendStr(k)(h.message(a))()}})(function(a){return b.sendStr(k)(f.printJson(f.printerString)(d.encodeJson(e)(a)))})(c[">>="](g.bindAff)(n(a)(p(l)))(q))}},b.post(k)(m.value0.serverUrl)(w);if(m.value0.method instanceof l.PUT)return w=function(l){return function(k){return g.runAff(function(a){return function(){r.log("Failed hostEndpoint POST on "+
(m.value0.serverUrl+h.message(a)))();return b.sendStr(k)(h.message(a))()}})(function(a){return b.sendStr(k)(f.printJson(f.printerString)(d.encodeJson(e)(a)))})(c[">>="](g.bindAff)(n(a)(p(l)))(q))}},b.put(k)(m.value0.serverUrl)(w);throw Error("Failed pattern match at Klikhut.Server.Core line 46, column 1 - line 49, column 1: "+[k.constructor.name,m.constructor.name,q.constructor.name]);}}}}}}};a.listen=b.listen;a.makeApp=b.makeApp})(PS["Klikhut.Server.Core"]=PS["Klikhut.Server.Core"]||{});
(function(a){var b=PS.Prelude,c=PS["Database.AnyDB"],e=PS["Klikhut.SQL"],d=PS["Klikhut.Model.Photobooth"],f=PS["Klikhut.Endpoint"],g=PS["Klikhut.Server.Core"],l=PS["Control.Monad.Eff.Exception"],h=PS["Control.Monad.Eff.Console"],m=PS["Control.Monad.Aff"],k=PS["Data.Argonaut.Encode"],r=PS["Data.Argonaut.Decode"],n=new d.Photobooth({computername:"yourcomputername",alias:"youralias",defaultprofile:"yourprofile"}),p=function(a){return"/"===a.url?b["return"](m.applicativeAff)("./static/index.html"):"/static/client.js"===
a.url?b["return"](m.applicativeAff)("./static/client.js"):b["return"](m.applicativeAff)(a.url)},q=new d.Photobooth({computername:"mycomputername",alias:"myalias",defaultprofile:"myprofile"}),t=function(a){return function(b){return e.insert(a)([b.value0.computername,b.value0.alias,b.value0.defaultprofile])}},u=new c.Sqlite3({filename:"klikhutdb",memory:!1}),v=function(a){return c.withConnection(u)(function(b){return c.execute_(t(d.table)(a.body))(b)})},x=function(a){var f=c.Query("Update "+(b.show(e.showTable)(d.table)+
(" set alias = '"+(a.body.value0.alias+("', defaultprofile = '"+(a.body.value0.defaultprofile+("'  where computername='"+(a.body.value0.computername+"'"))))))));return c.withConnection(u)(function(a){return c.execute_(f)(a)})},y=function(a){return c.withConnection(u)(function(a){return c.query_(d.photoboothIsForeign)(e.selectStar(d.table)(""))(a)})};a.updatePB=x;a.newPB=v;a.allPhotobooths=y;a.insertPB=t;a["static"]=p;a.main=function(){m.runAff(function(a){return h.log(b.show(l.showError)(a))})(b["const"](h.log("Initial SQL OK")))(c.withConnection(u)(function(a){return b.bind(m.bindAff)(c.execute_(e.dropTable(d.table))(a))(function(){return b.bind(m.bindAff)(c.execute_(e.createTable(d.table)(d.cols))(a))(function(){return b.bind(m.bindAff)(c.execute_(t(d.table)(q))(a))(function(){return c.execute_(t(d.table)(n))(a)})})})}))();
var a=g.makeApp();g.hostEndpoint(k.encodeJsonUnit)(r.decodeJsonNull)(k.encodeJsonArray(d.encodeJsonPhotobooth))(r.decodeArray(d.decodeJsonPhotobooth))(a)(f.getPhotobooths)(y)();g.hostEndpoint(d.encodeJsonPhotobooth)(d.decodeJsonPhotobooth)(k.encodeJsonUnit)(r.decodeJsonNull)(a)(f.postPhotobooths)(v)();g.hostEndpoint(d.encodeJsonPhotobooth)(d.decodeJsonPhotobooth)(k.encodeJsonUnit)(r.decodeJsonNull)(a)(f.putPhotobooths)(x)();g.hostFile(a)("*")(p)();g.listen(a)(8080)();return h.log("Starting server on "+
b.show(b.showInt)(8080))()};a.port=8080;a.yourbooth=n;a.mybooth=q;a.connectionInfo=u})(PS.Main=PS.Main||{});PS.Main.main();
